export const throwError = (error) => error.response.data.msg || 'Une erreur s\'est produite lors de l\'inscription.';
